import opcode

with open('opcode.h', 'w') as f:
	f.write('/* Generated by generate_opcode.py, do not edit */\n')
	f.write('#ifndef _TOOLS_OPCODE_H_\n')
	f.write('#define _TOOLS_OPCODE_H_\n')
	f.write('#define HAVE_ARUMENT	90\n')
	f.write('typedef enum {\n')
	for op in range(len(opcode.opname)):
		name = opcode.opname[op]
		if not name.startswith('<'):
			f.write('\t{0} = {1},\n'.format(name, op))

	f.write('} PyOpcode;\n')
	f.write('#endif\n')
